config/routes.rb
Rails.application.routes.draw do

  post 'subscription_checkout' => 'plans#subscription_checkout'

  resources :plans
  resources :subscriptions

  mount StripeEvent::Engine, at: '/stripe/webhooks'

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :plan
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  protect_from_forgery except: :webhooks
  require "stripe"

  def new

  end

  def create
    subscription = Stripe::Plan.create(
      amount: (params[:amount].to_i)*100,
      interval: params[:interval],
      name: params[:plan_name],
      currency: 'usd',
      trial_plan: nil,
      id: SecureRandom.uuid # This ensures that the plan is unique in stripe
    )
    #Save the response to your DB
    flash[:notice] = "Plan successfully created"
    redirect_to subscriptions_path
  end

  def index
    @stripe_list = Stripe::Plan.all
    @plans = @stripe_list[:data]
  end

  def subscription_checkout
    plan_id = params[:plan_id]
    plan = Stripe::Plan.retrieve(plan_id)
    #This should be created on signup.
    customer = Stripe::Customer.create(
            :description => "Customer for test@example.com",
            :source => params[:stripeToken],
            :email => params[:customer_email],
            :plan => params[:plan_id],
            :quantity => params[:price].to_i
          )
    # # Save this in your DB and associate with the user;s email
    User.create(email: params[:customer_email], customer_id: customer.id )

    flash[:notice] = "Successfully created a charge"
    redirect_to plans_path
  end

  # def webhooks
  #   begin
  #     event_json = JSON.parse(request.body.read)
  #     event_object = event_json['data']['object']
  #     #refer event types here https://stripe.com/docs/api#event_types
  #     case event_json['type']
  #       when 'invoice.payment_succeeded'
  #         handle_success_invoice event_object
  #       when 'invoice.payment_failed'
  #         handle_failure_invoice event_object
  #       when 'charge.failed'
  #         handle_failure_charge event_object
  #       when 'customer.subscription.deleted'
  #       when 'customer.subscription.updated'
  #     end
  #   rescue Exception => ex
  #     render :json => {:status => 422, :error => "Webhook call failed"}
  #     return
  #   end
  #   render :json => {:status => 200}
  # end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  require "stripe"
  def index
    @stripe_subscriptions_list = Stripe::Subscription.all()['data']
  end

  def edit
    @subscription = Stripe::Subscription.retrieve(params[:id])
  end

  def update
    subscription = Stripe::Subscription.retrieve(params[:id])
    subscription.quantity = params[:quantity]
    subscription.save
    redirect_to subscriptions_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subscription_helper.rb
module SubscriptionHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SubscriptionPlans</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/plans/index.html.erb
<div class="plan-container">
  <ul>
    <% @plans.each do |plan| %>
      <li class="plan">
        <div class="header">
          Plan name:
          <%= plan[:name] %>
        </div>
        <div class="price">
          Price:
          <%= (plan[:amount]/100) %>
        </div>
        <%= form_tag('/subscription_checkout', {method: :post, plan: plan}) do %>
          <input name="plan_id" type="hidden" value="<%= plan[:id] %>"></input>
          Enter customer email: <input name="customer_email" type="text"/>
          Cost of plan: <input name="price" type="number"/>
          <script class="stripe-button" data-amount="<%= (plan[:amount]) %>" data-currency="<%= plan[:currency] %>" data-email="customer@example.com" data-key="<%= STRIPE_CONFIG["#{Rails.env}"]['publishable_key'] %>" src="https://checkout.stripe.com/checkout.js"></script>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/plans/new.html.erb
<h1>Create new plan on Stripe</h1>
<%= form_tag('/subscriptions',{method: :post}) do %>
  <div class="form-group">
    <label>Plan name</label>
    <input name="plan_name" type="text"></input>
  </div>
  <div class="form-group">
    <label>Plan interval</label>
    <%= select_tag 'interval', options_for_select(['month', 'year']), multiple: false, :include_blank => true,  class: "form-control" %>
  </div>
  <div class="form-group">
    <label>Plan Value</label>
    <input name="amount" type="text"></input>
  </div>
  <button type="submit">Submit to Stripe</button>
<% end %>

app/views/subscriptions/edit.html.erb
<div>
  <label>Customer Email:</label>
  <%= User.find_by(customer_id: @subscription.customer).email %>
</div>
<div>
  <label>Plan:</label>
  <%= @subscription.plan.name %>
</div>
<div>
  <%= form_tag("/subscriptions/#{@subscription.id}", method: :put) do -%>
    <label>Quantity:</label>
    <input name="quantity" type="number">
    <div><%= submit_tag 'Update quantity' %></div>
  <% end -%>
</div>
<br/>

app/views/subscriptions/index.html.erb
<% @stripe_subscriptions_list.each do |subscription| %>
  <div>
    <label>Customer Email:</label>
    <%= User.find_by(customer_id: subscription.customer).email %>
  </div>
  <div>
    <label>Plan:</label>
    <%= subscription.plan.name %>
  </div>
  <div>
    <label>Quantity:</label>
    <%= subscription.quantity %>
  </div>
  <%= link_to 'Edit Quantity', edit_subscription_path(subscription.id) %>
  <br/>
<% end %>